server:
  port: 1666
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 123.249.19.24:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.249.19.24:3306/learndb1?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: maky
