server:
  port: 1555
spring:
  application:
    name: account-service
  cloud:
    nacos:
      discovery:
        server-addr: 123.249.19.24:8848
        #配置启用了鉴权，在客户端注册时，配置中需要nacos的账号/密码进行鉴权。否则在应用启动时，向nacos注册时就会报标题里面的错误。
        username: nacos
        password: nacos
      config:
        #具体原因https://blog.csdn.net/qq_37785549/article/details/132595431
        import-check:
          enabled: false
        server-addr: 123.249.19.24:8848
        #读取文件后缀
        file-extension: yml
        #是否自动刷新
        refresh-enabled: true
        #多配置文件配置，除了application.name外的nacos配置
        shared-configs:
          - data-id: redis.yml
            refresh: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.249.19.24:3306/db_account?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: maky
seata:
  enabled: true
  # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
  registry:
    type: Nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}
      #默认就是seata-server
      application: seata-server
  # 事务组，根据这个获取tc服务的cluster名称
  tx-service-group: seata-demo
  service:
    # 事务组与TC服务cluster集群的映射关系
    vgroup-mapping:
      seata-demo: default
  # 开启AT事务
  data-source-proxy-mode: XA



